{{/*
  * Bootstrap a deployment
  * It should always receive a dict as an argument
*/}}
{{- define "lib.core.deployment" -}} {{- /* define[0] */ -}}
---
# ---------------------------------------------------------------------
# -- This resource is managed by the allanger's helm library
# ---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- .metadata | nindent 2 }}
spec:
	{{- include "lib.core.deployment.spec" (dict "ctx" .ctx) | nindent 2 }}
{{- end -}} {{- /* /define[0] */ -}}

{{- define "lib.core.deployment.spec" -}} {{- /* define[0] */ -}}
replicas: {{ .ctx.Values.workload.replicas | default 1 }}
selector:
  matchLabels:
    {{- include "lib.helpers.selectorLabels" .ctx | nindent 6 }}
{{ include "lib.core.deployment.template" (dict "ctx" .ctx) }}
{{- end -}} {{- /* /define[0] */ -}}

{{- define "lib.core.deployment.template" -}} {{- /* define[0] */ -}}
template:
  metadata:
    labels:
      {{- include "lib.helpers.labels" .ctx | nindent 6 }}
    annotations:
{{ include "lib.helpers.hashes" (dict "env" .ctx.Values.env "files" .ctx.Values.files) | indent 6 }}
  spec:
    {{- include "lib.core.pod.securityContext" (dict "ctx" .ctx) | nindent 4 -}}
    {{- include "lib.core.pod.volumes" (dict "ctx" .ctx) | nindent 4 }}
    {{- include "lib.core.pod.containers" .ctx | nindent 4 }}
    {{- include "lib.core.pod.initContainers" . | nindent 4 }
{{- end -}} {{- /* /define[0] */ -}}
