# ---------------------------------------------------------------------
# A set of tests to be executed should be define via values
# ---------------------------------------------------------------------
---
